theme: custom-theme
data: 
  presse_logos: 
    - logo_path: /uploads/0-layout/presse-zeit.png
      link: /blog/unsere-experten-in-der-presse-zeit-online-schufa-und-identitätsdiebstahl/
      logo_seo_text: Presselogo Zeit Online
    - logo_path: /uploads/0-layout/presse-handelsblatt.png
      link: /blog/unsere-experten-in-der-presse-dr-tintemann-zu-thomas-lloyd-im-handelsblatt/
      logo_seo_text: Presselogo Handelsblatt
    - logo_path: /uploads/0-layout/presse-capital.png
      link: /blog/experten-in-der-presse-zitat-von-dr-tintemann-in-sachen-deutsche-öl-und-gas-s-a/
      logo_seo_text: Presselogo Capital
    - logo_path: /uploads/0-layout/presse-bild.png
      link: /blog/unsere-experten-in-der-presse-bild-zeitung-bild-telefon-aktion-immobilien/
      logo_seo_text: Presselogo Bild Zeitung
    - logo_path: /uploads/0-layout/presse-immozeitung.png
      link: /blog/unsere-experten-in-der-presse-rechtsanwalt-klevenhagen-zu-geldanlagen-bei-der-udi-in-der-immobilienzeitung/
      logo_seo_text: Presselogo Immobilienzeitung
    - logo_path: /uploads/0-layout/presse-anwaltsblatt.jpg
      link: /blog/unsere-experten-in-der-presse-dr-tintemann-im-berliner-anwaltsblatt/
      logo_seo_text: Presselogo Berliner Anwaltsblatt